config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'admin', 
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock', 
    registration: 'r',
    sign_up: 'sign_up' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root to: "main#index"

  # Unique
  delete 'photos/:id/purge/photographies/:photographie_id', to: 'photos#purge_photographie', as: 'purge_photo_contents'
  delete 'photos/:id/purge/graphismes/:graphisme_id', to: 'photos#purge_graphisme', as: 'purge_photo_elements'

  delete 'photographies/:id/delete_all', to: 'photographies#delete_all', as: 'delete_all_photographies'
  delete 'graphismes/:id/delete_all', to: 'graphismes#delete_all', as: 'delete_all_graphismes'

  # Contact
  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get '/contacts/sent'

  # Photographies
  resources :photographies do
    resources :contents
  end

  # Graphismes
  resources :graphismes do
    resources :elements
  end

  # Retouches
  resources :retouches
end

app/models/graphisme.rb
class Graphisme < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :elements, dependent: :destroy

  has_one_attached :photo, service: :cloudinary_graphismes
end

app/controllers/graphismes_controller.rb
class GraphismesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_graphisme, only: [:show, :edit, :update, :destroy]

  def index
    @graphismes = Graphisme.all
  end

  def delete_all
    @graphismes = Graphisme.all

    @graphismes.each do |graphisme|
      graphisme.destroy
    end

    @graphismes.delete_all
    redirect_to graphismes_path, status: :see_other
  end

  def show
    @previous_graphisme = Graphisme.where("id < ?", @graphisme.id).last
    @next_graphisme = Graphisme.where("id > ?", @graphisme.id).first
  end
    
  def new
    @graphisme = Graphisme.new
  end
    
  def create
    @graphisme = Graphisme.new(graphisme_params)

    if @graphisme.save
      redirect_to graphisme_path(@graphisme)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @graphisme.update(graphisme_params)
    redirect_to graphisme_path(@graphisme)
  end

  def destroy
    @graphisme.destroy
    redirect_to graphismes_path, status: :see_other
  end

  private

  def set_graphisme
    @graphisme = Graphisme.find(params[:id])
  end

  def graphisme_params
    params.require(:graphisme).permit(:name, :photo)
  end
end

app/helpers/graphismes_helper.rb
module GraphismesHelper
end

app/views/graphismes/edit.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for @graphisme do |f| %>
      <div class="formfor-form-container">
        <h1>Modification </h1>
        <hr>
        <%= f.label "Nom" %>
        <%= f.text_field :name, class: "formfor-field" %>
        <%= f.label "Photo principal" %>
        <%= f.file_field :photo, as: :file,
        data:{ controller: "photo-preview", action: "change->photo-preview#preview"} %>

        <div 
        id="photo-previews" 
        class="photographie_preview" 
        data-controller="photo-preview" 
        data-action="photo-preview#preview"
        >
        </div>

        <%= f.submit "Enregistrer", 
        data: { disabled_with: false,
        controller: "photo-preview",
        action:"click->photo-preview#clearPreviews" 
        },
        class: "form-submit-button formfor-button" %>
        <%= link_to graphismes_path do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/graphismes/index.html.erb
<div class="photographie-container">
  <div class="photographie-container-elements">
    <% if user_signed_in? %>
      <div class="photographie-buttons-container">
        <%= link_to new_graphisme_path, class: "photographie-add-button" do %>
          <i class="fa-solid fa-plus"></i> Ajouter
        <% end %>
        <% if @graphismes.present? %>
          <%= link_to delete_all_graphismes_path(@graphismes), class: "photographie-add-button red-button", data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer tous les graphismes ?"} do %>
            <i class="far fa-trash-alt"></i> Supprimer tout
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="photographie-grid-container">
      <div class="photographie-grid">
        <% @graphismes&.each do |graphisme| %>
          <div class="photographie-grid-wrapper">
            <% if user_signed_in? %>
              <div class="linked">
                <%= link_to graphisme_path(graphisme), class: "", data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer #{graphisme.name}"} do %>
                    <i class="far fa-trash-alt"></i>
                <% end %>
                <%= link_to edit_graphisme_path(graphisme), class: "" do %>
                    <i class="far fa-edit"></i>
                <% end %>
              </div>
            <% end %>
            <%= link_to graphisme_path(graphisme) do %>
              <div class="photographie-grid-element">
                <div class="photographie-photo-container">
                  <img class="photographie-photo" src="<%= cl_image_path "graphismes/" + graphisme.photo.key, :raw_transformation => "f_auto,q_50,h_400,c_fit" %>" alt="graphisme photo">
                </div>
                <div class="photographie-photo-name">
                  <p><%= graphisme.name %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/graphismes/new.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for @graphisme do |f| %>
      <div class="formfor-form-container">
        <h1>Nouvel element</h1>
        <hr>
        <%= f.label "Nom" %>
        <%= f.text_field :name, class: "formfor-field" %>
        <%= f.label "Photo principal" %>
        <%= f.file_field :photo, as: :file,
        data:{ controller: "photo-preview", action: "change->photo-preview#preview"} %>

        <div 
        id="photo-previews" 
        class="photographie_preview" 
        data-controller="photo-preview" 
        data-action="photo-preview#preview"
        >
        </div>

        <%= f.submit "Enregistrer", 
        data: { disabled_with: false,
        controller: "photo-preview",
        action:"click->photo-preview#clearPreviews" 
        },
        class: "form-submit-button formfor-button" %>
        <%= link_to graphismes_path do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/graphismes/show.html.erb
<div class="photographie-show" data-controller="image-fadein">
  <div class="graphisme-show-intro">
    <p><%= @graphisme.name %></p>
  </div>
  <div class="photographie-container">
    <div class="photographie-container-elements">
      <div class="photographie-buttons-container">
        <%= link_to graphismes_path, class: "photographie-add-button" do %>
          <i class="fas fa-undo-alt"></i> Retour
        <% end %>
        <% if user_signed_in? %>
          <%= link_to new_graphisme_element_path(@graphisme), class: "photographie-add-button" do %>
            <i class="fa-solid fa-plus"></i> Ajouter des photos
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="grid-photos-container">
    <% @graphisme.elements&.each do |element| %>
      <% element.photos&.each do |photo| %>
        <div class="grid-photo-wrapper fade-in" data-image-fadein-target='fadeinImageContainer'>
          <img src="<%= cl_image_path "graphismes/element/" + photo.key, :raw_transformation => "f_auto,q_50,w_1000,c_fit" %>" alt="graphisme photos">
          <%= link_to purge_photo_elements_path(photo, @graphisme), class: "linked", data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer cet élément ?"} do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="photographie-navigation fade-in <%= (@next_graphisme.present? && !@previous_graphisme.present?) ? "photographie-navigation-push-right" : "photographie-navigation-push-between" %>">
    <% if @previous_graphisme.present? %>
      <%= link_to "< " + @previous_graphisme.name, @previous_graphisme, class: "photographie-navigation-previous" %>
    <% end %>
    <% if @next_graphisme.present? %>
      <%= link_to @next_graphisme.name + " >", @next_graphisme, class: "photographie-navigation-next" %>
    <% end %>
  </div>
</div>