config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'admin', 
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock', 
    registration: 'r',
    sign_up: 'sign_up' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root to: "main#index"

  # Unique
  delete 'photos/:id/purge/photographies/:photographie_id', to: 'photos#purge_photographie', as: 'purge_photo_contents'
  delete 'photos/:id/purge/graphismes/:graphisme_id', to: 'photos#purge_graphisme', as: 'purge_photo_elements'

  delete 'photographies/:id/delete_all', to: 'photographies#delete_all', as: 'delete_all_photographies'
  delete 'graphismes/:id/delete_all', to: 'graphismes#delete_all', as: 'delete_all_graphismes'

  # Contact
  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get '/contacts/sent'

  # Photographies
  resources :photographies do
    resources :contents
  end

  # Graphismes
  resources :graphismes do
    resources :elements
  end

  # Retouches
  resources :retouches
end

app/controllers/photographies_controller.rb
class PhotographiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_photographie, only: [:show, :edit, :update, :destroy, :photos]

  def index
    @photographies = Photographie.all
  end

  def delete_all
    @photographies = Photographie.all

    @photographies.each do |photographie|
      photographie.destroy
    end

    @photographies.delete_all
    redirect_to photographies_path, status: :see_other
  end

  def show
    @previous_photographie = Photographie.where("id < ?", @photographie.id).last
    @next_photographie = Photographie.where("id > ?", @photographie.id).first
  end

  def new
    @photographie = Photographie.new
  end
    
  def create
    @photographie = Photographie.new(photographie_params)
  
    if @photographie.save
      redirect_to photography_path(@photographie)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @photographie.update(photographie_params)
    redirect_to photography_path(@photographie)
  end

  def destroy
    Cloudinary::Uploader.destroy(@photographie.photo.key)
    @photographie.destroy
    redirect_to photographies_path, status: :see_other
  end

  private

  def set_photographie
    @photographie = Photographie.find(params[:id])
  end

  def photographie_params
    params.require(:photographie).permit(:name, :description, :photo)
  end
end

app/helpers/photographies_helper.rb
module PhotographiesHelper
end

app/views/photographies/edit.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for @photographie do |f| %>
      <div class="formfor-form-container">
        <h1>Modification </h1>
        <hr>
        <%= f.label "Nom" %>
        <%= f.text_field :name, class: "formfor-field" %>
        <%= f.label "Description" %>
        <%= f.text_field :description, class: "formfor-field" %>
        <%= f.label "Photo principal" %>
        <%= f.file_field :photo, as: :file,
        data:{ controller: "photo-preview", action: "change->photo-preview#preview"} %>

        <div 
        id="photo-previews" 
        class="photographie_preview" 
        data-controller="photo-preview" 
        data-action="photo-preview#preview"
        >
        </div>

        <%= f.submit "Enregistrer", 
        data: { disabled_with: false,
        controller: "photo-preview",
        action:"click->photo-preview#clearPreviews" 
        },
        class: "form-submit-button formfor-button" %>
        <%= link_to photographies_path do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/photographies/index.html.erb
<div class="photographie-container">
  <div class="photographie-container-elements">
    <% if user_signed_in? %>
      <div class="photographie-buttons-container">
        <%= link_to new_photography_path, class: "photographie-add-button" do %>
          <i class="fa-solid fa-plus"></i> Ajouter
        <% end %>
        <% if @photographies.present? %>
          <%= link_to delete_all_photographies_path(@photographies), class: "photographie-add-button red-button", data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer toutes les photographies ?"} do %>
            <i class="far fa-trash-alt"></i> Supprimer tout
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="photographie-grid-container">
      <div class="photographie-grid">
        <% @photographies&.each do |photographie| %>
          <div class="photographie-grid-wrapper">
            <% if user_signed_in? %>
              <div class="linked">
                <%= link_to photography_path(photographie), class: "", data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer #{photographie.name} ?"} do %>
                    <i class="far fa-trash-alt"></i>
                <% end %>
                <%= link_to edit_photography_path(photographie), class: "" do %>
                    <i class="far fa-edit"></i>
                <% end %>
              </div>
            <% end %>
            <%= link_to photography_path(photographie) do %>
              <div class="photographie-grid-element">
                <div class="photographie-photo-container">
                  <img class="photographie-photo" src="<%= cl_image_path "photographies/" + photographie.photo.key, :raw_transformation => "f_auto,q_50,h_400,c_fit" %>" alt="photographie photo">
                </div>
                <div class="photographie-photo-name">
                  <p><%= photographie.name %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photographies/new.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for @photographie do |f| %>
      <% if @photographie.errors.any? %>
        <div class="error-container">
          <h2 class="error-title">Attention il y a <%= pluralize(@photographie.errors.count, "erreur") %> :</h2>
          <ul class="error-list">
            <% @photographie.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="formfor-form-container">
        <h1>Nouvel element photographie</h1>
        <hr>
        <%= f.label "Nom" %>
        <%= f.text_field :name, class: "formfor-field" %>
        <%= f.label "Description" %>
        <%= f.text_field :description, class: "formfor-field" %>
        <%= f.label "Photo principal" %>
        <%= f.file_field :photo, as: :file,
        data:{ controller: "photo-preview", action: "change->photo-preview#preview"} %>

        <div 
        id="photo-previews" 
        class="photographie_preview" 
        data-controller="photo-preview" 
        data-action="photo-preview#preview"
        >
        </div>

        <%= f.submit "Enregistrer", 
        data: { disabled_with: false,
        controller: "photo-preview",
        action:"click->photo-preview#clearPreviews" 
        },
        class: "form-submit-button formfor-button" %>
        <%= link_to photographies_path do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/photographies/show.html.erb
<div class="photographie-show" data-controller="image-fadein">
  <div class="photographie-show-intro">
    <img src="<%= cl_image_path "photographies/" + @photographie.photo.key, :raw_transformation => "f_auto,q_50,h_1280,c_fit" %>" alt="main photographie photo">
    <p><%= @photographie.description %></p>
  </div>
  <div class="photographie-container">
    <div class="photographie-container-elements">
      <div class="photographie-buttons-container">
        <%= link_to photographies_path, class: "photographie-add-button" do %>
          <i class="fas fa-undo-alt"></i> Retour
        <% end %>
        <% if user_signed_in? %>
          <%= link_to new_photography_content_path(@photographie), class: "photographie-add-button" do %>
            <i class="fa-solid fa-plus"></i> Ajouter des photos
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="grid-photos-container">
    <% @photographie.contents&.each do |content| %>
      <% content.photos&.each do |photo| %>
        <div class="grid-photo-wrapper fade-in" data-image-fadein-target='fadeinImageContainer'>
          <img src="<%= cl_image_path "photographies/content/" + photo.key, :raw_transformation => "f_auto,q_50,w_1000,c_fit" %>" alt="photographie photo">
          <% if user_signed_in? %>
            <%= link_to purge_photo_contents_path(photo, @photographie), class: "linked", data: {turbo_method: :delete, turbo_confirm: "Voulez-vous vraiment supprimer cet élément ?"} do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="photographie-navigation fade-in <%= (@next_photographie.present? && !@previous_photographie.present?) ? "photographie-navigation-push-right" : "photographie-navigation-push-between" %>">
    <% if @previous_photographie.present? %>
      <%= link_to "< " + @previous_photographie.name, @previous_photographie, class: "photographie-navigation-previous" %>
    <% end %>
    <% if @next_photographie.present? %>
      <%= link_to @next_photographie.name + " >", @next_photographie, class: "photographie-navigation-next" %>
    <% end %>
  </div>
</div>