config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'admin', 
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock', 
    registration: 'r',
    sign_up: 'sign_up' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root to: "main#index"

  # Unique
  delete 'photos/:id/purge/photographies/:photographie_id', to: 'photos#purge_photographie', as: 'purge_photo_contents'
  delete 'photos/:id/purge/graphismes/:graphisme_id', to: 'photos#purge_graphisme', as: 'purge_photo_elements'

  delete 'photographies/:id/delete_all', to: 'photographies#delete_all', as: 'delete_all_photographies'
  delete 'graphismes/:id/delete_all', to: 'graphismes#delete_all', as: 'delete_all_graphismes'

  # Contact
  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get '/contacts/sent'

  # Photographies
  resources :photographies do
    resources :contents
  end

  # Graphismes
  resources :graphismes do
    resources :elements
  end

  # Retouches
  resources :retouches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :surname,   validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   validate: true

  # def headers
  #   { 
  #     to: "spitemplar@gmail.com", # change this to be the email you want sent to
  #     subject: "Solenne-Carreras - Nouveau message de #{surname}",
  #     # Changer le mail dans l'environement de development
  #     from: %("#{name} #{surname}" <#{email}),  # change this to be the email it is coming from
  #     reply_to: %("#{name} #{surname}" <#{email}>) 
  #   }
  # end
end

app/models/content.rb
class Content < ApplicationRecord
  validates :photos, presence: true
  validate :validate_photos_filetype

  belongs_to :photographie

  has_many_attached :photos, service: :cloudinary_photographie_contents

  private

  def photo_attachement(index)
    target = photos[index]
    return unless photos.attached?

    if target.image?
      target.variant(resize_to_limit: [150, 150]).processed
    end
  end

  def validate_photos_filetype
    return unless photos.attached?
  
    photos.each do |photo|
      unless photo.image?
        errors.add(:photos, "must be an image")
      end
    end
  end
end

app/models/element.rb
class Element < ApplicationRecord
  validates :photos, presence: true
  validate :validate_photos_filetype

  belongs_to :graphisme

  has_many_attached :photos, service: :cloudinary_graphisme_elements

  private

  def photo_attachement(index)
    target = photos[index]
    return unless photos.attached?

    if target.image?
      target.variant(resize_to_limit: [150, 150]).processed
    end
  end

  def validate_photos_filetype
    return unless photos.attached?
  
    photos.each do |photo|
      unless photo.image?
        errors.add(:photos, "must be an image")
      end
    end
  end
end

app/models/graphisme.rb
class Graphisme < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :elements, dependent: :destroy

  has_one_attached :photo, service: :cloudinary_graphismes
end

app/models/photographie.rb
class Photographie < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true
  validates :photo, presence: true

  validate :validate_photo_filetype

  has_many :contents, dependent: :destroy

  has_one_attached :photo, service: :cloudinary_photographies

  private

  def photo_attachement(index)
    target = photo[index]
    return unless photos.attached?

    if target.image?
      target.variant(resize_to_limit: [150, 150]).processed
    end
  end

  def validate_photo_filetype
    return unless photo.attached?

    unless photo.image?
      errors.add(:photo, "must be an image")
    end
  end
end

app/models/retouche.rb
class Retouche < ApplicationRecord
  validates :before_photo, presence: true
  validates :after_photo, presence: true
  validate :validate_photo_filetype

  has_one_attached :before_photo, service: :cloudinary_retouches
  has_one_attached :after_photo, service: :cloudinary_retouches

  private

  def validate_photo_filetype
    return unless before_photo.attached? && after_photo.attached?

    unless before_photo.image? && after_photo.image?
      errors.add(:before_photo, "must be an image")
      errors.add(:after_photo, "must be an image")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :sent]
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if ContactMailer.contact(@contact).deliver
      redirect_to action: :sent
    else
      render :new, status: :unprocessable_entity
    end
  end

  def sent
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :authenticate_user!

  def purge_photographie
    photo = ActiveStorage::Attachment.find(params[:id])
    Cloudinary::Uploader.destroy(photo.key)
    photo.purge
  
    @photographie = Photographie.find(params[:photographie_id])

    redirect_to photography_path(@photographie)
  end

  def purge_graphisme
    photo = ActiveStorage::Attachment.find(params[:id])
    Cloudinary::Uploader.destroy(photo.key)
    photo.purge
  
    @graphisme = Photographie.find(params[:graphisme_id])

    redirect_to graphisme_path(@graphisme)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/graphismes_helper.rb
module GraphismesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/photographies_helper.rb
module PhotographiesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/retouches_helper.rb
module RetouchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solenne Carreras</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Photographe Paris. Portraitiste, Publicitaire. Studio photo, Post-production et retouche numérique.">    

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <link rel="preload" as="image" href="http://res.cloudinary.com/rztprog/">
  </head>

  <body class="body" data-controller="menu-burger" data-menu-burger-target='body'>
    <%= render 'shared/navbar' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/photographie_contents/new.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for [@photographie, @photographieContent] do |f| %>
      <% if @photographie.errors.any? %>
        <div class="error-container">
          <h2 class="error-title">Attention il y a <%= pluralize(@photographie.errors.count, "erreur") %> :</h2>
          <ul class="error-list">
            <% @photographie.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="formfor-form-container">
        <h1>Ajouter des photos à <%= @photographie.name %></h1>
        <hr>
        <%= f.label "Photos" %>
        <%= f.file_field :photo, as: :file %>

        <%= f.submit "Enregistrer", class: "form-submit-button formfor-button" %>
        <%= link_to photography_path(@photographie) do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="carousel" data-controller="carousel" data-carousel-target="carouselHome">
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/Capture_d_%C3%A9cran_2020-09-06_%C3%A0_13.09.23_lwyree.png",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Packaging.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/SolenneCarreras_2022-11-10_Pizzou_Issy_42_lfhbi8.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Photographie culinaire.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/DSC04979_copie_1_lnnpzt.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Reportage photo.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/Photo__SolenneCarreras__iamsolenne_NormalMagazine_StefanieRenoma_2018_3_xb48gl.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Photographie artistique.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/SolenneCarreras_2022_AppartementCavalaire_21_x6zlnd.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Photographie Immobilière.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/DSC08473_copie_vnlcrj.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Packshots produits.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/OddPears2_mqwjpn.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Créations de logos.
      </div>
    </div>
  </div>
  <div class="item">
    <div class="item-img">
      <%= cl_image_tag("wetransfer_photo-home-page-slider-horizontal_2022-12-30_1559/Capture_d_%C3%A9cran_2022-11-24_%C3%A0_12.00.34_bsz03w.png",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "image-carousel") %>
      <div class="item-info">
        Identité visuelle.
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="flash-container">
  <% if notice %>
    <div class="flash-error" role="alert">
      <!--
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      -->
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="flash-error" role="alert">
      <!--
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      -->
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <a class="footer-social" href="http://www.instagram.com/iamsolenne">@iamsolenne</a>
  <a class="footer-mail" href="mailto: solennecarreras@gmail.com">solennecarreras@gmail.com</a>
  <p class="footer-rights">All rights reserved to Solenne Carreras © 2022</p>
</footer>

app/views/shared/_intro.html.erb
<div class="text-intro-container">
  <h1 class="text-intro">Tout commence par une idée.</h1>
</div>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2021_07_Loire_Valley_Lodges_196_1_w7gkq9.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2021_09_LaMaisonVraj_16_1_ib5x1i.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2021_09_LaMaisonVraj_62_1_bjulq8.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/HUILE_-_DSC04114_2020_1_dele2y.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2021_09_LaMaisonVraj_59_1_f4kivn.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2021_07_Loire_Valley_Lodges_297_ea8trw.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2022_Shangri-La_173_r2q9we.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2022_Kalank_33_a4uhhv.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>
<figure class="figure-image">
  <%= cl_image_tag("wetransfer_photos-home-page-partie-haute_2022-12-30_1551/SolenneCarreras_2022_Marignan_61_mbteh7.jpg",
  :raw_transformation => "f_auto,q_50,h_400,c_fit",
  class: "image-top") %>
</figure>

app/views/shared/_navbar.html.erb
<nav class="navbar" data-controller="avatar-dropdown navbar" data-navbar-target='nav' data-menu-burger-target='nav'>
  <div>
    <%= link_to "Solenne Carreras", root_path, class: "navbar-title-link" %>
  </div>
  <ul class="navbar-list" data-menu-burger-target='desktopList' data-navbar-target="navbarList">
    <li><%= link_to "PHOTOGRAPHIE", photographies_path, class: "#{'current-list' if controller_name == 'photographies'}" %></li>
    <!--
    <li><%= link_to "RETOUCHES", retouches_path, class: "#{'current-list' if controller_name == 'retouches'}"  %></li>
    <li><%= link_to "GRAPHISME", graphismes_path, class: "#{'current-list' if controller_name == 'graphismes'}"  %></li>
    -->
    <li><%= link_to "CONTACT", contacts_path, class: "#{'current-list' if controller_name == 'contacts'}"  %></li>
    <li class="navbar-icon">
      <a href="http://instagram.com/iamsolenne" class="navbar-title-link" target="_blank">
        <i class="fa-brands fa-instagram"></i>
      </a>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <div class="signin-desktop">
          <i class="fa-solid fa-arrow-right-to-bracket iconconnect" data-action="click->avatar-dropdown#action"></i>
          <div class="dropdownmenu d-none" data-avatar-dropdown-target='dropdown'>
            <%= link_to "Deconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdownitem" %>
          </div>
        </div>
        <div class="signin-mobile">
          <!--
          <p data-action="click->avatar-dropdown#actionmobile">COMPTE</p>
          <div class="d-none" data-avatar-dropdown-target='dropdownmobile'>
            <%= link_to "Panel", "#", class: "mobile-li" %>
            <%= link_to "Deconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "mobile-li" %>
          </div>
          -->
          <%= link_to "DECONNEXION", destroy_user_session_path, data: {turbo_method: :delete}, class: "mobile-li" %>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="burger-container" data-action="click->menu-burger#action" data-menu-burger-target='burger'>
    <span class="burger-icon">
      <span data-menu-burger-target='span1'></span>
      <span data-menu-burger-target='span2'></span>
      <span data-menu-burger-target='span3'></span>
    </span>
  </div>
</nav>

app/views/shared/_services.html.erb
<h2 class="services-part-title">Nos services</h2>
<div class="services-grid" data-controller="image-fadein accordion">
  <div>
    <div class="services-grid-image-container fade-in" data-image-fadein-target='fadeinImageContainer'>
      <%= cl_image_tag("wetransfer_photos-home-page-3-rubriques_2022-12-30_1602/SolenneCarreras_2021_07_Loire_Valley_Lodges_280_1_k02qmd.jpg",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "services-grid-image") %>
    </div>
    <div class="services-description">
      <div class="services-description-title" data-action="click->accordion#action" data-index="0">
        <h3 data-index="0">Photographie</h3>
        <div class="services-cross" data-index="0">
          <span></span>
          <span data-accordion-target='accordionCross'></span>
        </div>
      </div>
      <ul class="accordion-list" data-accordion-target='accordionList' data-index="0">
        <li>Photographie immobilière</li>
        <li>Culinaire & restauration</li>
        <li>Packshots produits</li>
        <li>Évènementiel</li>
      </ul>
    </div>
  </div>
  <div>
    <div class="services-grid-image-container fade-in" data-image-fadein-target='fadeinImageContainer' >
      <%= cl_image_tag("wetransfer_photos-home-page-3-rubriques_2022-12-30_1602/Capture_d_%C3%A9cran_2022-11-24_%C3%A0_11.18.57_mjymlc.png",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "services-grid-image") %>
    </div>
    <div class="services-description" >
      <div class="services-description-title" data-action="click->accordion#action" data-index="1">
        <h3 data-index="1">Retouches</h3>
        <div class="services-cross" data-index="1">
          <span></span>
          <span data-accordion-target='accordionCross'></span>
        </div>
      </div>
      <ul class="accordion-list" data-accordion-target='accordionList' data-index="1">
        <li>Retouches numériques de tout type de photographies 
        (portraits, mode, packshots produits, immobilier, etc).</li>
      </ul>
    </div>
  </div>
  <div>
    <div class="services-grid-image-container fade-in" data-image-fadein-target='fadeinImageContainer'>
      <%= cl_image_tag("wetransfer_photos-home-page-3-rubriques_2022-12-30_1602/Capture_d_%C3%A9cran_2022-11-24_%C3%A0_11.21.52_gqdnm3.png",
      :raw_transformation => "f_auto,q_50,w_1000,c_fit",
      class: "services-grid-image") %>
    </div>
    <div class="services-description">
      <div class="services-description-title" data-action="click->accordion#action" data-index="2">
        <h3 data-index="2">Graphisme</h3>
        <div data-index="2" class="services-cross">
          <span></span>
          <span data-accordion-target='accordionCross'></span>
        </div>
      </div>
      <ul class="accordion-list" data-accordion-target='accordionList' data-index="2">
        <li>Création de logotype</li>
        <li>Identité visuelle </li>
        <li>Packaging</li>
      </ul>
    </div>
  </div>
</div>