config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'admin', 
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification',
    unlock: 'unlock', 
    registration: 'r',
    sign_up: 'sign_up' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root to: "main#index"

  # Unique
  delete 'photos/:id/purge/photographies/:photographie_id', to: 'photos#purge_photographie', as: 'purge_photo_contents'
  delete 'photos/:id/purge/graphismes/:graphisme_id', to: 'photos#purge_graphisme', as: 'purge_photo_elements'

  delete 'photographies/:id/delete_all', to: 'photographies#delete_all', as: 'delete_all_photographies'
  delete 'graphismes/:id/delete_all', to: 'graphismes#delete_all', as: 'delete_all_graphismes'

  # Contact
  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get '/contacts/sent'

  # Photographies
  resources :photographies do
    resources :contents
  end

  # Graphismes
  resources :graphismes do
    resources :elements
  end

  # Retouches
  resources :retouches
end

app/controllers/retouches_controller.rb
class RetouchesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_retouche, only: [:show, :edit, :update, :destroy]

  def index
    @retouches = Retouche.all
  end

  def show
    @retouches = Retouche.all
    if @retouche == nil 
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @retouche = Retouche.new
  end
    
  def create
    @retouche = Retouche.new(retouche_params)
  
    if @retouche.save
      redirect_to retouches_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @retouche.update(retouche_params)
    redirect_to retouches_path
  end

  def destroy
    Cloudinary::Uploader.destroy(@retouche.before_photo.key)
    Cloudinary::Uploader.destroy(@retouche.after_photo.key)
    @retouche.destroy
    redirect_to retouches_path, status: :see_other
  end

  private

  def set_retouche
    @retouche = Retouche.find(params[:id])
  end

  def retouche_params
    params.require(:retouche).permit(:before_photo, :after_photo)
  end
end

app/helpers/retouches_helper.rb
module RetouchesHelper
end

app/views/retouches/edit.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for @retouche do |f| %>
      <div class="formfor-form-container">
        <h1>Modification Retouche <%= @retouche.id %></h1>
        <hr>
        <%= f.label "Photo avant" %>
        <%= f.file_field :before_photo, as: :file %>
        <%= f.label "Photo après" %>
        <%= f.file_field :after_photo, as: :file %>

        <%= f.submit "Enregistrer", class: "form-submit-button formfor-button" %>
        <%= link_to retouches_path do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/retouches/index.html.erb
<div class="photographie-container" data-controller="slider-comparison" data-slider-comparison-target="slider">
  <div class="retouches-container">
    <% if user_signed_in? %>
      <div class="photographie-buttons-container">
        <%= link_to new_retouch_path, class: "photographie-add-button" do %>
          <i class="fa-solid fa-plus"></i> Ajouter
        <% end %>
      </div>
    <% end %>
    <div class="img-comp-container">
      <div class="img-comp-img">
        <img class="" src="<%= cl_image_path "retouches/" + @retouches[0].after_photo.key %>" alt="retouche photo 1">
      </div>
      <div class="img-comp-img img-comp-overlay">
        <img class="" src="<%= cl_image_path "retouches/" + @retouches[0].before_photo.key %>" alt="retouche photo 2">
      </div>
    </div>
    <div class="retouche-grid-buttons">
      <% @retouches&.each do |retouche| %>
        <%= link_to retouch_path(retouche) do %> 
          <img class="retouche-grid-buttons-img" src="<%= cl_image_path "retouches/" + retouche.after_photo.key %>" alt="retouche photo">
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/retouches/new.html.erb
<div class="form-part">
  <div class="formfor-container">
    <%= form_for @retouche do |f| %>
      <% if @retouche.errors.any? %>
        <div class="error-container">
          <h2 class="error-title">Attention il y a <%= pluralize(@retouche.errors.count, "erreur") %> :</h2>
          <ul class="error-list">
            <% @retouche.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="formfor-form-container">
        <h1>Nouvel element retouche</h1>
        <hr>
        <%= f.label "Photo avant" %>
        <%= f.file_field :before_photo, as: :file %>
        <%= f.label "Photo après" %>
        <%= f.file_field :after_photo, as: :file %>

        <%= f.submit "Enregistrer", class: "form-submit-button formfor-button" %>
        <%= link_to retouches_path do %>
          <i class="fas fa-undo-alt form-submit-button"> Retour en arriere</i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/retouches/show.html.erb
<div class="photographie-container" data-controller="slider-comparison" data-slider-comparison-target="slider">
  <div class="retouches-container">
    <% if user_signed_in? %>
      <div class="photographie-buttons-container">
        <%= link_to new_retouch_path, class: "photographie-add-button" do %>
          <i class="fa-solid fa-plus"></i> Ajouter
        <% end %>
      </div>
    <% end %>
    <div class="img-comp-container">
      <div class="img-comp-img">
        <img class="" src="<%= cl_image_path "retouches/" + @retouche.after_photo.key %>" alt="retouche photo 1">
      </div>
      <div class="img-comp-img img-comp-overlay">
        <img class="" src="<%= cl_image_path "retouches/" + @retouche.before_photo.key %>" alt="retouche photo 2">
      </div>
    </div>
    <div class="retouche-grid-buttons">
      <% @retouches&.each do |retouche| %>
        <%= link_to retouch_path(retouche) do %> 
          <img class="retouche-grid-buttons-img" src="<%= cl_image_path "retouches/" + retouche.after_photo.key %>" alt="retouche photo">
        <% end %>
      <% end %>
    </div>
  </div>
</div>